# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/giuliac/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),giuliac)

$(call add-radio-file-sha1-checked,radio/abl.img,f15ca4be5a112852997a897fd744b61b90ba3278)
$(call add-radio-file-sha1-checked,radio/aop.img,9d3fecc7c614558c0543f518ac058ed726f5d43c)
$(call add-radio-file-sha1-checked,radio/aop_config.img,8c87cddf82189885c14ee437d0ac1b6ed053a270)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,d6e66bb29aa0d3b2fb78bee6267943d3af8153cb)
$(call add-radio-file-sha1-checked,radio/cpucp.img,0599cea7cc565b44c1e772dfd785784f63a6e8c3)
$(call add-radio-file-sha1-checked,radio/cpucp_dtb.img,59ab7288e6e2705d493bad1b90ec67a53f43ba98)
$(call add-radio-file-sha1-checked,radio/devcfg.img,1e1f50078cee0840b937619a231435342707dd9c)
$(call add-radio-file-sha1-checked,radio/dsp.img,72075bb397712d2b7753e2a8654cf8e5c2313602)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,be0695deec1cb80da7f60f24b8457dca49a5d43f)
$(call add-radio-file-sha1-checked,radio/featenabler.img,4209f061943a7db7faf87d2c85adc38886cd6e7b)
$(call add-radio-file-sha1-checked,radio/hyp.img,aedac8089a50856bf865bd7568fb2ffc7d3e1f86)
$(call add-radio-file-sha1-checked,radio/imagefv.img,36777373f718e3c3bb2a9c1db926978a02519fa3)
$(call add-radio-file-sha1-checked,radio/keymaster.img,3ce943277d30f62434a019c0ead4d7f3fbf1b8f1)
$(call add-radio-file-sha1-checked,radio/modem.img,3c0a0b42103ec4992b2bcb988a21129c3c041192)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,2a0a3bc41fa77874e80515aaee0a151fd7ea2756)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,f665404b3d032370d95d7f890d48670f9c96ede5)
$(call add-radio-file-sha1-checked,radio/qupfw.img,50b901a050053e360a27562856820effaaa615d4)
$(call add-radio-file-sha1-checked,radio/shrm.img,f7f0a4a33a0339065c60b9c8cc95a139936d1d51)
$(call add-radio-file-sha1-checked,radio/splash.img,07e9cda27d7d55806370294443d78ef887e32d2b)
$(call add-radio-file-sha1-checked,radio/tz.img,2e843fea73ddac08f4ee0899fc75c234d552ccc8)
$(call add-radio-file-sha1-checked,radio/uefi.img,df2048b9fac30d2b069a381ce37cfc43b11d017f)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,70a2b3f063e506bbac59adc8ab28fa180a6892bb)
$(call add-radio-file-sha1-checked,radio/xbl.img,2f46c0a22819eaff910bdc99d98f60fa6e06ab79)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a6e0ed887bd5a67740b567b7b8b5eefa16ccfb25)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,b658ba1ce8eaecb71c46ae7eaa7539c269b03aa0)

endif
