# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/giuliac/setup-makefiles.sh

AB_OTA_PARTITIONS += abl
BOARD_CUSTOMIMAGES_PARTITION_LIST += abl
BOARD_ABL_IMAGE_LIST += vendor/oneplus/giuliac/radio/abl.img

AB_OTA_PARTITIONS += aop
BOARD_CUSTOMIMAGES_PARTITION_LIST += aop
BOARD_AOP_IMAGE_LIST += vendor/oneplus/giuliac/radio/aop.img

AB_OTA_PARTITIONS += aop_config
BOARD_CUSTOMIMAGES_PARTITION_LIST += aop_config
BOARD_AOP_CONFIG_IMAGE_LIST += vendor/oneplus/giuliac/radio/aop_config.img

AB_OTA_PARTITIONS += bluetooth
BOARD_CUSTOMIMAGES_PARTITION_LIST += bluetooth
BOARD_BLUETOOTH_IMAGE_LIST += vendor/oneplus/giuliac/radio/bluetooth.img

AB_OTA_PARTITIONS += cpucp
BOARD_CUSTOMIMAGES_PARTITION_LIST += cpucp
BOARD_CPUCP_IMAGE_LIST += vendor/oneplus/giuliac/radio/cpucp.img

AB_OTA_PARTITIONS += cpucp_dtb
BOARD_CUSTOMIMAGES_PARTITION_LIST += cpucp_dtb
BOARD_CPUCP_DTB_IMAGE_LIST += vendor/oneplus/giuliac/radio/cpucp_dtb.img

AB_OTA_PARTITIONS += devcfg
BOARD_CUSTOMIMAGES_PARTITION_LIST += devcfg
BOARD_DEVCFG_IMAGE_LIST += vendor/oneplus/giuliac/radio/devcfg.img

AB_OTA_PARTITIONS += dsp
BOARD_CUSTOMIMAGES_PARTITION_LIST += dsp
BOARD_DSP_IMAGE_LIST += vendor/oneplus/giuliac/radio/dsp.img

AB_OTA_PARTITIONS += engineering_cdt
BOARD_CUSTOMIMAGES_PARTITION_LIST += engineering_cdt
BOARD_ENGINEERING_CDT_IMAGE_LIST += vendor/oneplus/giuliac/radio/engineering_cdt.img

AB_OTA_PARTITIONS += featenabler
BOARD_CUSTOMIMAGES_PARTITION_LIST += featenabler
BOARD_FEATENABLER_IMAGE_LIST += vendor/oneplus/giuliac/radio/featenabler.img

AB_OTA_PARTITIONS += hyp
BOARD_CUSTOMIMAGES_PARTITION_LIST += hyp
BOARD_HYP_IMAGE_LIST += vendor/oneplus/giuliac/radio/hyp.img

AB_OTA_PARTITIONS += imagefv
BOARD_CUSTOMIMAGES_PARTITION_LIST += imagefv
BOARD_IMAGEFV_IMAGE_LIST += vendor/oneplus/giuliac/radio/imagefv.img

AB_OTA_PARTITIONS += keymaster
BOARD_CUSTOMIMAGES_PARTITION_LIST += keymaster
BOARD_KEYMASTER_IMAGE_LIST += vendor/oneplus/giuliac/radio/keymaster.img

AB_OTA_PARTITIONS += modem
BOARD_CUSTOMIMAGES_PARTITION_LIST += modem
BOARD_MODEM_IMAGE_LIST += vendor/oneplus/giuliac/radio/modem.img

AB_OTA_PARTITIONS += oplus_sec
BOARD_CUSTOMIMAGES_PARTITION_LIST += oplus_sec
BOARD_OPLUS_SEC_IMAGE_LIST += vendor/oneplus/giuliac/radio/oplus_sec.img

AB_OTA_PARTITIONS += oplusstanvbk
BOARD_CUSTOMIMAGES_PARTITION_LIST += oplusstanvbk
BOARD_OPLUSSTANVBK_IMAGE_LIST += vendor/oneplus/giuliac/radio/oplusstanvbk.img

AB_OTA_PARTITIONS += qupfw
BOARD_CUSTOMIMAGES_PARTITION_LIST += qupfw
BOARD_QUPFW_IMAGE_LIST += vendor/oneplus/giuliac/radio/qupfw.img

AB_OTA_PARTITIONS += shrm
BOARD_CUSTOMIMAGES_PARTITION_LIST += shrm
BOARD_SHRM_IMAGE_LIST += vendor/oneplus/giuliac/radio/shrm.img

AB_OTA_PARTITIONS += splash
BOARD_CUSTOMIMAGES_PARTITION_LIST += splash
BOARD_SPLASH_IMAGE_LIST += vendor/oneplus/giuliac/radio/splash.img

AB_OTA_PARTITIONS += tz
BOARD_CUSTOMIMAGES_PARTITION_LIST += tz
BOARD_TZ_IMAGE_LIST += vendor/oneplus/giuliac/radio/tz.img

AB_OTA_PARTITIONS += uefi
BOARD_CUSTOMIMAGES_PARTITION_LIST += uefi
BOARD_UEFI_IMAGE_LIST += vendor/oneplus/giuliac/radio/uefi.img

AB_OTA_PARTITIONS += uefisecapp
BOARD_CUSTOMIMAGES_PARTITION_LIST += uefisecapp
BOARD_UEFISECAPP_IMAGE_LIST += vendor/oneplus/giuliac/radio/uefisecapp.img

AB_OTA_PARTITIONS += xbl
BOARD_CUSTOMIMAGES_PARTITION_LIST += xbl
BOARD_XBL_IMAGE_LIST += vendor/oneplus/giuliac/radio/xbl.img

AB_OTA_PARTITIONS += xbl_config
BOARD_CUSTOMIMAGES_PARTITION_LIST += xbl_config
BOARD_XBL_CONFIG_IMAGE_LIST += vendor/oneplus/giuliac/radio/xbl_config.img

AB_OTA_PARTITIONS += xbl_ramdump
BOARD_CUSTOMIMAGES_PARTITION_LIST += xbl_ramdump
BOARD_XBL_RAMDUMP_IMAGE_LIST += vendor/oneplus/giuliac/radio/xbl_ramdump.img

